workflows:
  my-workflow:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Generate Android files
        script: flutter create . --platforms=android
      - name: Get dependencies
        script: flutter pub get
      - name: Build App
        script: flutter build apk --release --enable-experiment=dot-shorthands
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
