workflows:
  my-workflow:
    name: Android Build
    environment:
      flutter: stable
    scripts:
      - name: Generate Android files
        script: flutter create . --platforms=android
      - name: Build App
        script: flutter --enable-experiment=dot-shorthands build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
