workflows:
  my-workflow:
    name: Android Build
    environment:
      flutter: stable
      vars:
        DART_CLI_OPTIONS: "--enable-experiment=dot-shorthands"
    scripts:
      - name: Generate Android files
        script: flutter create . --platforms=android
      - name: Build App
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      
